name: Despliegue automático a InfinityFree

on:
  push:
    branches:
      - main  # Cambia 'main' si usas otra rama

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Descargar el código
      uses: actions/checkout@v4

    - name: Subir archivos a InfinityFree mediante FTP
      uses: SamKirkland/FTP-Deploy-Action@v4.3.5
      with:
        server: ftpupload.net  # Servidor FTP de InfinityFree
        username: ${{ secrets.FTP_USERNAME }}
        password: ${{ secrets.FTP_PASSWORD }}
        local-dir: ./  # Carpeta del código en GitHub
        server-dir: /htdocs/  # Carpeta en el servidor de InfinityFree
