name: Desplegar en InfinityFree

on:
   push:
     branches:
      - master
jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout del código
      uses: actions/checkout@v4

    - name: Configurar conexión FTP
      uses: SamKirkland/FTP-Deploy-Action@4.3.0
      with:
        ftp-server: ftpupload.net
        ftp-username: ${{ secrets.FTP_USERNAME }}
        ftp-password: ${{ secrets.FTP_PASSWORD }}
        local-dir: ./  
        server-dir: /htdocs/
