name: Despliegue en InfinityFree

on:
  push:
    branches:
      - master  # Cambia 'main' si usas otra rama

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Descargar el código
      uses: actions/checkout@v4

    - name: Subir archivos a InfinityFree mediante FTP
      uses: SamKirkland/FTP-Deploy-Action@4.3.0
      with:
        ftp-server: ftpupload.net  # Servidor FTP de InfinityFree
        ftp-username: ${{ secrets.FTP_USERNAME }}
        ftp-password: ${{ secrets.FTP_PASSWORD }}
        local-dir: ./  # Carpeta del código en GitHub
        server-dir: /htdocs/  # Carpeta en el servidor de InfinityFree
